### ISSUE TITLE
Look like /lib is missing in the /wwwroot directory

### ISSUE THREAD

**Issue by JanSichula** [damienbod/AspNet5SQLite#1]
Hello,

it looks like /lib is missing in the /wwwroot directory and so app only displays blank white page.

https://www.facebook.com/jan.sichula
https://twitter.com/JanSichula

**Comment by damienbod** [comment]
Hi Jan, 

Thanks for the feedback

I have a look and fix it tonight

Greetings Damien

**Comment by damienbod** [comment]
This should be fixed now, could you close the issue if its ok for you

Again, thanks for your feedback

Greetings Damien
